"""empty message

Revision ID: 204282730d6f
Revises: 55077b587ead
Create Date: 2024-01-30 22:35:34.059366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204282730d6f'
down_revision = '55077b587ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
